### ISSUE TITLE
Correción TP1 - Grupo2_Mixto

### ISSUE THREAD

**Issue by FrancoPaesani** [FrancoPaesani/2020_K2002_Grupo_2#1]
Buenas profe, está listo el TP1 para la correción.

**Comment by santiagoferreiros** [comment]
Esitmados

@FrancoPaesani @tomytinez @crisedu250198 @TimoBel @MateoRasso @crisedu250198 

Muy buen trabajo ! Felicitaciones
Nota 9

Algunas observaciones
El archivo entregado tiene extención .cpp , cuando la consiga pide que sea un archivo .c
Estuve revisando el código y está muy bien, quizás en algunas partes puede resumirse, reducirse y hacerse de modo más simplificado. Para que lo tengan en cuenta. Pero está perfecto y cumple con las funcionalidades.
Los printf están muy bien para ir viendo lo que sucede pero no es lo pedido. Solo debía estar en el archivo de salida.

Saludos ! Excelente !
