### ISSUE TITLE
Corrección Trabajo Practico 2

### ISSUE THREAD

**Issue by crisedu250198** [FrancoPaesani/2020_K2002_Grupo_2#2]
@santiagoferreiros Hola profesor, acabamos de subir el .c  y .exe del trabajo practico 2.
Saludos!!

**Comment by santiagoferreiros** [comment]
Estimados,

Hicieron un muy buen trabajo.

Lo que pude notar es que en TT solo están los números, pero no está cargada la información respecto a ESTADO_SIGUIENTE , CADENAPUSH.

Eso entiendo que lo hicieron dentro de unos IF. La idea de la TT es que acumule toda la información que requiere el AFP sin necesidad de luego tener que utilizar condicionales.

De todos modos, la entrega cumple perfecto la funcionalidad. Pero tengan esto presente porque luego se utilizará =)

Nota: 8

@crisedu250198 @tomytinez @TimoBel @FrancoPaesani
