### ISSUE TITLE
Entrega Trabajo Práctico N° 3

### ISSUE THREAD

**Issue by MateoRasso** [FrancoPaesani/2020_K2002_Grupo_2#4]
Solicitamos corrección del  trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Excelente trabajo estimados,

Un detalle del deporte

No se llaman VARIABLES decimales, ni octales, ni caracter. Se denominan CONSTANTE decimales, octales, etc.

El resto está muy bien

Nota: 9

Saludos,

Santiago
